version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ams-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ams-local
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: